name: Docker DB CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Hardee9284
          MYSQL_DATABASE: test_db
          MYSQL_USER: root
          MYSQL_PASSWORD: Hardee9284
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_URL: jdbc:mysql://localhost:3306/test_db
      DB_USER: root
      DB_PASSWORD: Hardee9284
      PRODUCT_SERVICE_URL: http://localhost:8081

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h "127.0.0.1" --silent; then
              echo "MySQL ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Build and Test
        run: mvn clean verify